config/routes.rb
GtalumniTest::Application.routes.draw do
  resources :registrations do
    resources :registration_responses
  end
  
  root :to => 'registrations#index'

end

app/models/registration.rb
class Registration < ActiveRecord::Base
  has_many :registration_responses
end

app/models/registration_response.rb
class RegistrationResponse < ActiveRecord::Base
  belongs_to :registration
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/registration_responses_controller.rb
class RegistrationResponsesController < ApplicationController
  before_filter :find_registration
  
  # GET /registration_responses
  # GET /registration_responses.json
  def index
    @registration_responses = @registration.registration_responses

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @registration_responses }
    end
  end

  # GET /registration_responses/1
  # GET /registration_responses/1.json
  def show
    @registration_response = @registration.registration_responses.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @registration_response }
    end
  end

  # GET /registration_responses/new
  # GET /registration_responses/new.json
  def new
    @registration_response = @registration.registration_responses.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @registration_response }
    end
  end

  # GET /registration_responses/1/edit
  def edit
    @registration_response = @registration.registration_responses.find(params[:id])
  end

  # POST /registration_responses
  # POST /registration_responses.json
  def create
    @registration_response = @registration.registration_responses.build(params[:registration_response])

    respond_to do |format|
      if @registration_response.save
        format.html { redirect_to [@registration, @registration_response], notice: 'Registration response was successfully created.' }
        format.json { render json: @registration_response, status: :created, location: @registration_response }
      else
        format.html { render action: "new" }
        format.json { render json: @registration_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /registration_responses/1
  # PUT /registration_responses/1.json
  def update
    @registration_response = @registration.registration_responses.find(params[:id])

    respond_to do |format|
      if @registration_response.update_attributes(params[:registration_response])
        format.html { redirect_to [@registration, @registration_response], notice: 'Registration response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @registration_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registration_responses/1
  # DELETE /registration_responses/1.json
  def destroy
    @registration_response = @registration.registration_responses.find(params[:id])
    @registration_response.destroy

    respond_to do |format|
      format.html { redirect_to registration_registration_responses_url(@registration) }
      format.json { head :no_content }
    end
  end
  
private
  def find_registration
    @registration = Registration.find(params[:registration_id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  # GET /registrations
  # GET /registrations.json
  def index
    @registrations = Registration.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @registrations }
    end
  end

  # GET /registrations/1
  # GET /registrations/1.json
  def show
    @registration = Registration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @registration }
    end
  end

  # GET /registrations/new
  # GET /registrations/new.json
  def new
    @registration = Registration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @registration }
    end
  end

  # GET /registrations/1/edit
  def edit
    @registration = Registration.find(params[:id])
  end

  # POST /registrations
  # POST /registrations.json
  def create
    @registration = Registration.new(params[:registration])

    respond_to do |format|
      if @registration.save
        format.html { redirect_to @registration, notice: 'Registration was successfully created.' }
        format.json { render json: @registration, status: :created, location: @registration }
      else
        format.html { render action: "new" }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /registrations/1
  # PUT /registrations/1.json
  def update
    @registration = Registration.find(params[:id])

    respond_to do |format|
      if @registration.update_attributes(params[:registration])
        format.html { redirect_to @registration, notice: 'Registration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrations/1
  # DELETE /registrations/1.json
  def destroy
    @registration = Registration.find(params[:id])
    @registration.destroy

    respond_to do |format|
      format.html { redirect_to registrations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registration_responses_helper.rb
module RegistrationResponsesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
  <head>
    <title>GtalumniTest</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="description" content="website description">
    <meta name="keywords" content="website keywords, website keywords">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
  </head>
  <body>
    <div id="main">
      <div id="header">
        <div id="logo">
          <div id="logo_text">
            <!-- class="logo_colour", allows you to change the colour of the text -->
            <h1>
              <a href="/"><span class="logo_colour">GTAA Web Developer Test</span></a>
            </h1>
            <h2>
            </h2>
          </div>
        </div>
        <div id="menubar">
          
        </div>
      </div>
      <div id="site_content">
        <div id="content">
          <%= yield %>
        </div>
      </div>
      <div id="footer">
        <p>
          Copyright © simplestyle_3 | <a href="http://validator.w3.org/check?uri=referer">HTML5</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.html5webtemplates.co.uk">design from HTML5webtemplates.co.uk</a><!--%@##--> Design provided by <a href="http://www.freewebtemplates.com">Free Website Templates</a>.<!--##@%-->
        </p>
      </div>
      <p>
        &nbsp;
      </p>
    </div>
  </body>
</html>

app/views/registration_responses/_form.html.erb
<%= form_for([@registration, @registration_response]) do |f| %>
  <% if @registration_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registration_response.errors.count, "error") %> prohibited this registration_response from being saved:</h2>

      <ul>
      <% @registration_response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :response1, @registration.question1 %><br />
    <%= f.text_field :response1 %>
  </div>
  <div class="field">
    <%= f.label :response2, @registration.question2 %><br />
    <%= f.text_field :response2 %>
  </div>
  <div class="field">
    <%= f.label :response3, @registration.question3 %><br />
    <%= f.text_field :response3 %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/registration_responses/edit.html.erb
<h1>Editing registration_response</h1>

<%= render 'form' %>

<%= link_to 'Show', [@registration, @registration_response] %> |
<%= link_to 'Back', registration_registration_responses_path(@registration) %>

app/views/registration_responses/index.html.erb
<h1>Registration Responses for <%= @registration.name unless @registration.name.nil? %></h1>

<table>
  <tr>
    <th>Response1</th>
    <th>Response2</th>
    <th>Response3</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @registration_responses.each do |registration_response| %>
  <tr>
    <td><%= registration_response.response1 %></td>
    <td><%= registration_response.response2 %></td>
    <td><%= registration_response.response3 %></td>
    <td><%= link_to 'Show', [@registration, registration_response] %></td>
    <td><%= link_to 'Edit', edit_registration_registration_response_path(@registration, registration_response) %></td>
    <td><%= link_to 'Destroy', [@registration, registration_response], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', registrations_path %> | 
<%= link_to 'New Registration response', new_registration_registration_response_path(@registration) %>

app/views/registration_responses/new.html.erb
<h1>New registration_response</h1>

<%= render 'form' %>

<%= link_to 'Back', registration_registration_responses_path(@registration) %>

app/views/registration_responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Response1:</b>
  <%= @registration_response.response1 %>
</p>

<p>
  <b>Response2:</b>
  <%= @registration_response.response2 %>
</p>

<p>
  <b>Response3:</b>
  <%= @registration_response.response3 %>
</p>


<%= link_to 'Edit', edit_registration_registration_response_path(@registration, @registration_response) %> |
<%= link_to 'Back', registration_registration_responses_path(@registration) %>